FROM ubuntu:trusty
MAINTAINER Nicholas Colbert <nicholas.colbert@ticketmaster.com>
RUN apt-get update && apt-get install -y python python-dev python-distribute python-pip

RUN apt-get update && apt-get install -y git python python-dev python-pip curl
RUN curl https://raw.githubusercontent.com/45cali/seeker/master/config/app/build.sh | sh






