FROM ubuntu:trusty
MAINTAINER Nicholas Colbert <nicholas.colbert@ticketmaster.com>
RUN apt-get update && apt-get install -y curl
RUN curl https://raw.githubusercontent.com/45cali/seeker/mysql/config/app/build.sh | sh






